let groups = [
  {
    name: "A",
    teams: [
      {
        name: "Qatar",
        rank: 51,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Ecudaor",
        rank: 46,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Senegal",
        rank: 20,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Netherlands",
        rank: 10,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
    ],
  },
  {
    name: "B",
    teams: [
      {
        name: "England",
        rank: 5,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Iran",
        rank: 21,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "USA",
        rank: 15,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Ukraine",
        rank: 27,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
    ],
  },
  {
    name: "C",
    teams: [
      {
        name: "Argentina",
        rank: 4,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Saudi Arabia",
        rank: 49,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Mexico",
        rank: 9,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Poland",
        rank: 26,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
    ],
  },
  {
    name: "D",
    teams: [
      {
        name: "France",
        rank: 3,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Peru",
        rank: 22,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Denmark",
        rank: 11,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Tunisia",
        rank: 35,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
    ],
  },
  {
    name: "E",
    teams: [
      {
        name: "Spain",
        rank: 7,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "New Zealaand",
        rank: 101,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Germany",
        rank: 12,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Japan",
        rank: 23,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
    ],
  },
  {
    name: "F",
    teams: [
      {
        name: "Belgium",
        rank: 2,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Canada",
        rank: 38,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Morocco",
        rank: 24,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Croatia",
        rank: 16,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
    ],
  },
  {
    name: "G",
    teams: [
      {
        name: "Brazil",
        rank: 1,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Serbia",
        rank: 25,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Switzerland",
        rank: 14,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Cameroon",
        rank: 37,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
    ],
  },
  {
    name: "H",
    teams: [
      {
        name: "Portugal",
        rank: 8,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Ghana",
        rank: 60,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Uruguay",
        rank: 13,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
      {
        name: "Korea Republic",
        rank: 29,
        wins: 0,
        loses: 0,
        draws: 0,
        points: 0,
        goals: 0,
        received: 0,
        matches: [],
      },
    ],
  },
];
export default groups;
